name: Docker publish

on:
  push:
    paths:
      - .github/workflows/buildx.yml.yml
      - Makefile
      - build/*/Dockerfile
      - Dockerfile.version
    branches:
      - 'main'

jobs:
  buildx:
    runs-on: ubuntu-latest
    allow-failure: true

    strategy:
      matrix:
        component:
          - gitlab-ce
          - gitlab-runner-helper

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
        with:
          driver: docker-container
          driver-opts: network=host

      - uses: docker/login-action@v1
        name: Login docker.io
        with:
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}

      - name: buildx ${{ matrix.component }}
        run: make buildx-${{ matrix.component }}
